# Generated by Django 2.2.3 on 2019-07-28 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Board', '0002_auto_20190728_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='post',
            name='lng',
        ),
    ]
