# Generated by Django 2.2.3 on 2019-07-29 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Board', '0004_auto_20190729_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='address',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
