# Generated by Django 2.2.3 on 2019-08-03 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Board', '0006_applicants_participants_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Confirm',
            field=models.BooleanField(default=False),
        ),
    ]
