# Generated by Django 2.2.3 on 2019-08-07 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Board', '0007_post_confirm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='ourFemaleNumber',
        ),
        migrations.RemoveField(
            model_name='post',
            name='ourMaleNumber',
        ),
    ]
