# Generated by Django 2.2.3 on 2019-07-21 09:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nickname', models.CharField(blank=True, max_length=15)),
                ('birth', models.DateField()),
                ('gender', models.CharField(choices=[('F', 'female'), ('M', 'male')], max_length=1)),
                ('phone', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='path/')),
                ('intro', models.TextField(blank=True, help_text='Introduce yourself')),
                ('relationships', models.ManyToManyField(related_name='related_to', through='accounts.Relationship', to='accounts.Signup', verbose_name='relation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.AddField(
            model_name='relationship',
            name='from_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_person', to='accounts.Signup'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='to_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_person', to='accounts.Signup'),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.TextField()),
                ('stars', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('reviewee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reviewee', to='accounts.Signup', verbose_name='reviewee')),
                ('reviewer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer', to='accounts.Signup', verbose_name='reviewer')),
            ],
        ),
    ]
