# Generated by Django 2.2.3 on 2019-08-01 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190721_1850'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
